services:
  dftbopt_api:
    build: .
    container_name: dftbopt_api_container
    ports:
      - "1990:8000"
    volumes:
      - ./app:/code/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # Add these settings to increase resources for the container
    shm_size: '4gb'  # Increase shared memory size
    ulimits:
      stack: -1    # Set unlimited stack size
      nofile:
        soft: 65536
        hard: 65536